/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSpaceRouteImport } from './routes/user-space'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as LoanApplicationRouteImport } from './routes/loan-application'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UserSpaceRoute = UserSpaceRouteImport.update({
  id: '/user-space',
  path: '/user-space',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanApplicationRoute = LoanApplicationRouteImport.update({
  id: '/loan-application',
  path: '/loan-application',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/loan-application': typeof LoanApplicationRoute
  '/testimonials': typeof TestimonialsRoute
  '/user-space': typeof UserSpaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/loan-application': typeof LoanApplicationRoute
  '/testimonials': typeof TestimonialsRoute
  '/user-space': typeof UserSpaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/eligibility': typeof EligibilityRoute
  '/faq': typeof FaqRoute
  '/loan-application': typeof LoanApplicationRoute
  '/testimonials': typeof TestimonialsRoute
  '/user-space': typeof UserSpaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/loan-application'
    | '/testimonials'
    | '/user-space'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/loan-application'
    | '/testimonials'
    | '/user-space'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/eligibility'
    | '/faq'
    | '/loan-application'
    | '/testimonials'
    | '/user-space'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  EligibilityRoute: typeof EligibilityRoute
  FaqRoute: typeof FaqRoute
  LoanApplicationRoute: typeof LoanApplicationRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UserSpaceRoute: typeof UserSpaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-space': {
      id: '/user-space'
      path: '/user-space'
      fullPath: '/user-space'
      preLoaderRoute: typeof UserSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-application': {
      id: '/loan-application'
      path: '/loan-application'
      fullPath: '/loan-application'
      preLoaderRoute: typeof LoanApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  EligibilityRoute: EligibilityRoute,
  FaqRoute: FaqRoute,
  LoanApplicationRoute: LoanApplicationRoute,
  TestimonialsRoute: TestimonialsRoute,
  UserSpaceRoute: UserSpaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
